[[LibArchive]]
arch = "aarch64"
git-tree-sha1 = "a7f8dab9cdf1cd5c466316f49c9d95ede895ac91"
os = "macos"

    [[LibArchive.download]]
    sha256 = "bdfc40b62a09623ceb498db34ac6d7f6643493d0d7c91ab870b0e33b64f93807"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.1+0/LibArchive.v3.8.1.aarch64-apple-darwin.tar.gz"
[[LibArchive]]
arch = "aarch64"
git-tree-sha1 = "89a04caa25734c33e16e142e8124f7f1eb2eca5a"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "5500e9eebc0d2a5b2daa985957ada6250a42c756f7ca2766f90a3f8e3d906778"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.1+0/LibArchive.v3.8.1.aarch64-linux-gnu.tar.gz"
[[LibArchive]]
arch = "aarch64"
git-tree-sha1 = "65638e4ec4b0fd59d5c1b8f93bd38c33d2801db7"
libc = "musl"
os = "linux"

    [[LibArchive.download]]
    sha256 = "6741c64199229813ce7b2f1051a99cd8fba1230744186694a9edc8e971754391"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.1+0/LibArchive.v3.8.1.aarch64-linux-musl.tar.gz"
[[LibArchive]]
arch = "aarch64"
git-tree-sha1 = "8c5880397d4de473d13c8cf9fc0df8845d08c9de"
os = "freebsd"

    [[LibArchive.download]]
    sha256 = "b2d805cefe75ff1fb6e2ed934d4d979a00cd963ac17da0b1a09f287c765d1888"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.1+0/LibArchive.v3.8.1.aarch64-unknown-freebsd.tar.gz"
[[LibArchive]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "14ac3570c9dd6c7742af7cbbc0a5874c56f5fd7e"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "4d302426f9731ef7ea6de7ef03990e6bd458aa8fe9e94f4bf86b2ce5de3d5210"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.1+0/LibArchive.v3.8.1.armv6l-linux-gnueabihf.tar.gz"
[[LibArchive]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b056190f79b5d6d3ddedbdccee445a39b116894c"
libc = "musl"
os = "linux"

    [[LibArchive.download]]
    sha256 = "13cd40052a4cf1497247349c9ef39d49579a97499404bd05c7b41f5b73449a51"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.1+0/LibArchive.v3.8.1.armv6l-linux-musleabihf.tar.gz"
[[LibArchive]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ac59293b9c9932a74f451f8ceba1c20a11812757"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "76656f0f4154a70d67817b7f9fef5dc8cf4d88dbbb62234c48f30f65a7a9ee97"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.1+0/LibArchive.v3.8.1.armv7l-linux-gnueabihf.tar.gz"
[[LibArchive]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "58a2fb08b9e13e51c66e8fdeb06451c96597f55d"
libc = "musl"
os = "linux"

    [[LibArchive.download]]
    sha256 = "ae426986e149671f0191c11bdadae8d38a26abb69543346d7798d3e15b537389"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.1+0/LibArchive.v3.8.1.armv7l-linux-musleabihf.tar.gz"
[[LibArchive]]
arch = "i686"
git-tree-sha1 = "ba146ec3e74691f088645afcc111e7809e67fe67"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "5dc41e4a9651820d82214b296a302005a3345992cd6682338a331f075d9f63d8"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.1+0/LibArchive.v3.8.1.i686-linux-gnu.tar.gz"
[[LibArchive]]
arch = "i686"
git-tree-sha1 = "cf132352b4dec5b16e324a99f449fdee7b60e812"
libc = "musl"
os = "linux"

    [[LibArchive.download]]
    sha256 = "cd28cc940e30768427ed77f0224bb40d8c2ffc399cde57b44759a398b9376f3e"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.1+0/LibArchive.v3.8.1.i686-linux-musl.tar.gz"
[[LibArchive]]
arch = "i686"
git-tree-sha1 = "47b1d1be4c5c9d4ced63c90b9b571eb98f5590ef"
os = "windows"

    [[LibArchive.download]]
    sha256 = "b29f41d9892cf63dcde8f82ef657e4a8201b07a67481594af46b3eca0da9750e"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.1+0/LibArchive.v3.8.1.i686-w64-mingw32.tar.gz"
[[LibArchive]]
arch = "powerpc64le"
git-tree-sha1 = "1ac4660a69bf694a3b9a287f7cbb220acbb9b25c"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "19d0846c8a6d219b5b2dbeef2fe7d5a433d9ccdd6f0c171083e076b7a3f46943"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.1+0/LibArchive.v3.8.1.powerpc64le-linux-gnu.tar.gz"
[[LibArchive]]
arch = "riscv64"
git-tree-sha1 = "c6afe931f1fd9b9d4ba02fd3205f28979d3b5d41"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "ae5d901d637259ce26d5aba9b1238535ad44fb52020737c8e96aaed1466a0d36"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.1+0/LibArchive.v3.8.1.riscv64-linux-gnu.tar.gz"
[[LibArchive]]
arch = "x86_64"
git-tree-sha1 = "99946c43ee1e75234c5fc2bcf24923e3d82a459d"
os = "macos"

    [[LibArchive.download]]
    sha256 = "2c8bd82c05055bf8a6cac32d25a19b658d7e4217544ab908b51217d58cce4eab"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.1+0/LibArchive.v3.8.1.x86_64-apple-darwin.tar.gz"
[[LibArchive]]
arch = "x86_64"
git-tree-sha1 = "e934cdb4b8dc911a801e7d484201d513e7cf1984"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "b321c09fb8701d1eb8c447c914188e60c637df7ad99a2e89b6eb066d33ec8bbc"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.1+0/LibArchive.v3.8.1.x86_64-linux-gnu.tar.gz"
[[LibArchive]]
arch = "x86_64"
git-tree-sha1 = "ad759a8dd36f7d63d7b71cf5faef3ec782510b93"
libc = "musl"
os = "linux"

    [[LibArchive.download]]
    sha256 = "f88aa1a1f256746671b1c4d5397a513885cc1b71dfb8b1120364fded0ff81680"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.1+0/LibArchive.v3.8.1.x86_64-linux-musl.tar.gz"
[[LibArchive]]
arch = "x86_64"
git-tree-sha1 = "936c12d54e1ce0bdc5e93d3423819910c5e23651"
os = "freebsd"

    [[LibArchive.download]]
    sha256 = "091a8ccf709acdb940922fdfb2ef58afa91ec1109375ea084cba2ae61fb094e5"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.1+0/LibArchive.v3.8.1.x86_64-unknown-freebsd.tar.gz"
[[LibArchive]]
arch = "x86_64"
git-tree-sha1 = "babb1422e105540ca343fe005aba3347693beade"
os = "windows"

    [[LibArchive.download]]
    sha256 = "156626a4c67e695e13a8ac041b50aa41b193f1f99cc3198edbc1e352b72ab18d"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.1+0/LibArchive.v3.8.1.x86_64-w64-mingw32.tar.gz"
