[[LibArchive]]
arch = "aarch64"
git-tree-sha1 = "734c1986c30a94a1e7f66748bf66058753c9b301"
os = "macos"

    [[LibArchive.download]]
    sha256 = "bdad8ede6d617afae92bb2b57febbe29a613fa09ab034788b8180fdce002d50f"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.3+0/LibArchive.v3.8.3.aarch64-apple-darwin.tar.gz"
[[LibArchive]]
arch = "aarch64"
git-tree-sha1 = "49a45f9fe0115395d6d453643e1b762463970087"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "1d27c782a1ca79d649c448a9c8d418f15e6433102cf994626c89b221e4505761"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.3+0/LibArchive.v3.8.3.aarch64-linux-gnu.tar.gz"
[[LibArchive]]
arch = "aarch64"
git-tree-sha1 = "82d1bd37ed10dc6cd1d07e22d79ef37ac48add3f"
libc = "musl"
os = "linux"

    [[LibArchive.download]]
    sha256 = "2b4091f307cb26e73c3e6227273b5219b35e2f611f6bc759e39dd4052f917012"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.3+0/LibArchive.v3.8.3.aarch64-linux-musl.tar.gz"
[[LibArchive]]
arch = "aarch64"
git-tree-sha1 = "3cd06148e211cdb3510c0c8eea9f1d2ea02e56e5"
os = "freebsd"

    [[LibArchive.download]]
    sha256 = "ffc0abdde83f6914f9aa1c943fd9cca058c060a64fff9b6bcc1cd33e7490dd5a"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.3+0/LibArchive.v3.8.3.aarch64-unknown-freebsd.tar.gz"
[[LibArchive]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dbd020aa7d7c9e82fd201b2944afcb50856d4860"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "7fdaeed0c7b5f86789dbf213c067290f69f71f47cc765df8440a4932449670b2"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.3+0/LibArchive.v3.8.3.armv6l-linux-gnueabihf.tar.gz"
[[LibArchive]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d78d50bd92b5471ed27d8466b5d801af5d18a5aa"
libc = "musl"
os = "linux"

    [[LibArchive.download]]
    sha256 = "d9724eaac049abf917536b1242fb8b1fa59acaf341b3f985937fb3930ab35763"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.3+0/LibArchive.v3.8.3.armv6l-linux-musleabihf.tar.gz"
[[LibArchive]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "48c5db844ed4051c88f990f795db9c94ff5856f0"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "c939a2de387090d5ed39e841ecb0b9f786571420e817e7f515c2d3ad7a5ee1f6"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.3+0/LibArchive.v3.8.3.armv7l-linux-gnueabihf.tar.gz"
[[LibArchive]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c7228b2daffaf1f24ae44d5733b2c8d50e1ab049"
libc = "musl"
os = "linux"

    [[LibArchive.download]]
    sha256 = "901cb76a9eabc898c5c1d6175401f0fc69134bffc55af6e7b68fd7d1cc4d7364"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.3+0/LibArchive.v3.8.3.armv7l-linux-musleabihf.tar.gz"
[[LibArchive]]
arch = "i686"
git-tree-sha1 = "0a35b38483518bb7d0d0cb13185b6dd1e77bc838"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "d6aac327918799f8d9afe8791bde499e3650c465705f43ed55a82a9adee59611"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.3+0/LibArchive.v3.8.3.i686-linux-gnu.tar.gz"
[[LibArchive]]
arch = "i686"
git-tree-sha1 = "18d13a2335f5e8ec1adba1293e65d3d1e47e4180"
libc = "musl"
os = "linux"

    [[LibArchive.download]]
    sha256 = "84caa2698b350a871a07d881b05936f17b2dd20727837f1ddb3df6dbe54bba48"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.3+0/LibArchive.v3.8.3.i686-linux-musl.tar.gz"
[[LibArchive]]
arch = "i686"
git-tree-sha1 = "cd6f4aa318540ca2b18743cedcbd959b8b7f86e3"
os = "windows"

    [[LibArchive.download]]
    sha256 = "18059fe261bce04101ce7ee822d8075b5aa217733bbb220e8f71cfcb601ee663"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.3+0/LibArchive.v3.8.3.i686-w64-mingw32.tar.gz"
[[LibArchive]]
arch = "powerpc64le"
git-tree-sha1 = "4a3f44438a2117781ff323c239b02f9c703e4c28"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "e0c75264203d9ce3c3420d7b0607677d14e4f689ba6788f10baba719f26cfaaa"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.3+0/LibArchive.v3.8.3.powerpc64le-linux-gnu.tar.gz"
[[LibArchive]]
arch = "riscv64"
git-tree-sha1 = "8819f091e78cdd5ed640c978fad63be39bc1ff0f"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "07998ac1222628aeab8621be9029b33c48c4f9c8478b7c843278cec94f5693ce"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.3+0/LibArchive.v3.8.3.riscv64-linux-gnu.tar.gz"
[[LibArchive]]
arch = "x86_64"
git-tree-sha1 = "01ef8dae0ab2d48de4836f409e4597c9503d7fc6"
os = "macos"

    [[LibArchive.download]]
    sha256 = "1babe0ebbb6ed9bc52513fb7471ca6346ba577daa32b149d09b46baa1d33439a"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.3+0/LibArchive.v3.8.3.x86_64-apple-darwin.tar.gz"
[[LibArchive]]
arch = "x86_64"
git-tree-sha1 = "238eee8078e0f6224cb0505f17922da1d9b376ee"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "d58e24f7626ffd5ea84a77a8e16895e213cf5e029c6c3ab2457817079178fcaa"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.3+0/LibArchive.v3.8.3.x86_64-linux-gnu.tar.gz"
[[LibArchive]]
arch = "x86_64"
git-tree-sha1 = "5dd8915d22c38d0229fa85e77c921f0e16075531"
libc = "musl"
os = "linux"

    [[LibArchive.download]]
    sha256 = "06436ce41537a7502dc1ab22c6c106d6337a08a4d85f79253c4830e22bcbabea"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.3+0/LibArchive.v3.8.3.x86_64-linux-musl.tar.gz"
[[LibArchive]]
arch = "x86_64"
git-tree-sha1 = "d61b9f607d621b41081bc0b8264f3b09a7cb33c3"
os = "freebsd"

    [[LibArchive.download]]
    sha256 = "2166ed3298310b8e5704ff82b8c647962e29c4c3fc67ee2c0ab77bb157eae599"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.3+0/LibArchive.v3.8.3.x86_64-unknown-freebsd.tar.gz"
[[LibArchive]]
arch = "x86_64"
git-tree-sha1 = "582806723cafe6462df4cc14ea281589552f6136"
os = "windows"

    [[LibArchive.download]]
    sha256 = "6b7a013960aae32eed37efe3c6929dcf3be37703d1c93de29b6a2b0a381333d3"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.3+0/LibArchive.v3.8.3.x86_64-w64-mingw32.tar.gz"
