[[LibArchive]]
arch = "aarch64"
git-tree-sha1 = "62e70993abf577c31511e8dd4e323920a220dc81"
os = "macos"

    [[LibArchive.download]]
    sha256 = "480511e7aa6d649b313d0b87e28f6aa6f6a64409e5562c8f9c632244c93287ff"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.2+0/LibArchive.v3.8.2.aarch64-apple-darwin.tar.gz"
[[LibArchive]]
arch = "aarch64"
git-tree-sha1 = "6482b7b4957e0a732aa9ce165c6516d5d3e04516"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "c88518f0387538fbf79e1910c4b2ec3f1e2b58c868a5653a85c3b0197155a920"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.2+0/LibArchive.v3.8.2.aarch64-linux-gnu.tar.gz"
[[LibArchive]]
arch = "aarch64"
git-tree-sha1 = "de710ca95bc484aac2829447636f2ef308699768"
libc = "musl"
os = "linux"

    [[LibArchive.download]]
    sha256 = "cb41dbbdf4533e2e9d4dfb8f0fe473c60fed3037d15c7504abdf7aa047804e72"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.2+0/LibArchive.v3.8.2.aarch64-linux-musl.tar.gz"
[[LibArchive]]
arch = "aarch64"
git-tree-sha1 = "01879c708cc3b51cfe2d9751708265363a0e0a93"
os = "freebsd"

    [[LibArchive.download]]
    sha256 = "f5d076d99982a1ab8d1d13beac64318ce1f2f96f7224e2aa1ef92a911dc4af01"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.2+0/LibArchive.v3.8.2.aarch64-unknown-freebsd.tar.gz"
[[LibArchive]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9dec2bed4b8ee9bc0906c50711c55fdb3edfb24d"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "f548e83a607e5dec7256bfd06afe711b0780e02279e2c5cdcd37feddb7d28599"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.2+0/LibArchive.v3.8.2.armv6l-linux-gnueabihf.tar.gz"
[[LibArchive]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a4ff10df20f072bc05b92c9473511db9aee9182d"
libc = "musl"
os = "linux"

    [[LibArchive.download]]
    sha256 = "b4ff9aca22e6f593ad11e66c854c521d35710452466c2ca7d3a096ddfcd7c3cf"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.2+0/LibArchive.v3.8.2.armv6l-linux-musleabihf.tar.gz"
[[LibArchive]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0b80f0deed0e883b7105b21f1690b8217b868600"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "25260661b1275635763b9ecbe71821485d6154aa7d61572cf849549cca578b7a"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.2+0/LibArchive.v3.8.2.armv7l-linux-gnueabihf.tar.gz"
[[LibArchive]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4d0ee22c61d551c09bb070f5db99ec93f3ea4556"
libc = "musl"
os = "linux"

    [[LibArchive.download]]
    sha256 = "b78c931500490aa7b3972376553fcf895c7e38c075df04bd8788635a32b0dfa8"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.2+0/LibArchive.v3.8.2.armv7l-linux-musleabihf.tar.gz"
[[LibArchive]]
arch = "i686"
git-tree-sha1 = "46d9bcccad536b6372d1fb9702ccb6f9463c057c"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "71b2c670f35fb2aed8cb3054199f0373ef394b283f58d98f017b72fd7185970a"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.2+0/LibArchive.v3.8.2.i686-linux-gnu.tar.gz"
[[LibArchive]]
arch = "i686"
git-tree-sha1 = "c0287542c0232f7ff324ef0301abe176cb197720"
libc = "musl"
os = "linux"

    [[LibArchive.download]]
    sha256 = "48057669ecc803776267b2ba6e2fac1d9df8419e37b3f16ce08a716432b4de84"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.2+0/LibArchive.v3.8.2.i686-linux-musl.tar.gz"
[[LibArchive]]
arch = "i686"
git-tree-sha1 = "888fbfae18ee7512440fe11737959947ddf6014d"
os = "windows"

    [[LibArchive.download]]
    sha256 = "ab8d02deced608425ab8879d683ebcf5636ba3b24082bb2beea710a2d8ae6de2"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.2+0/LibArchive.v3.8.2.i686-w64-mingw32.tar.gz"
[[LibArchive]]
arch = "powerpc64le"
git-tree-sha1 = "dfe6e71c3ea5dd213bb52ae84694be51bb6e2b38"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "85cb4191fe66b0410eece82e928ed4bfd5199ca2196fb7c90437f1db18429289"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.2+0/LibArchive.v3.8.2.powerpc64le-linux-gnu.tar.gz"
[[LibArchive]]
arch = "riscv64"
git-tree-sha1 = "f255f2b81a019bec4347041cb4149d3aa358d260"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "bfac4fcbd4ce58fe9a4cda7d27c391296b5fe3417783ad7e190fc55442af31c6"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.2+0/LibArchive.v3.8.2.riscv64-linux-gnu.tar.gz"
[[LibArchive]]
arch = "x86_64"
git-tree-sha1 = "3ac51c3e8ddd92852a6f0781a2a05a181065b0ca"
os = "macos"

    [[LibArchive.download]]
    sha256 = "0e2419f947e7c879fc84a975709cf9fb3738863e9714767ec83052f38b94f2e0"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.2+0/LibArchive.v3.8.2.x86_64-apple-darwin.tar.gz"
[[LibArchive]]
arch = "x86_64"
git-tree-sha1 = "986bef64e8114ab832eba56754c68a0d0d9069c6"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "74dc90787609e7e396ac8dadba4d6378c9b7d1b06562fe11412721adc4d85093"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.2+0/LibArchive.v3.8.2.x86_64-linux-gnu.tar.gz"
[[LibArchive]]
arch = "x86_64"
git-tree-sha1 = "06a99b34b43d2070ef35cfe591ee32d175ad00ee"
libc = "musl"
os = "linux"

    [[LibArchive.download]]
    sha256 = "2a56d7292d7877463d4d50a775d7b539ea8585ce7c85b505a851db5c9be38a7d"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.2+0/LibArchive.v3.8.2.x86_64-linux-musl.tar.gz"
[[LibArchive]]
arch = "x86_64"
git-tree-sha1 = "a77b967100e08ff06a8bcdb021a0c11f14201cb1"
os = "freebsd"

    [[LibArchive.download]]
    sha256 = "d9edf2d797e26baa20327596b0e494333d93c7742b01259aaf445977d2f23da2"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.2+0/LibArchive.v3.8.2.x86_64-unknown-freebsd.tar.gz"
[[LibArchive]]
arch = "x86_64"
git-tree-sha1 = "07080f7db275c2195ce937fcdc466e5ea8d3acf0"
os = "windows"

    [[LibArchive.download]]
    sha256 = "c768b441e171047c75af54b186343cb6fcf5aea54777cbc44064307e5d55a8e3"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.2+0/LibArchive.v3.8.2.x86_64-w64-mingw32.tar.gz"
